name: NPM publish CD workflow

on:
  release:
    types: [published]

jobs:
  build:
    environment: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        node:
          - 14

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g npm
      - run: npm install
      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "npm@dfinity.org"
      # build the project
      - run: npm run build --workspaces
      # run tests just in case
      - run: npm test
      # Exit if github tag doesn't start with v
      - run: if [[ "$GITHUB_REF" != *"refs/tags/v"* ]]; then
      - run: exit 1
      - run: fi
      # update versions and dependencies using tag
      - run: npm run version -- ${GITHUB_REF#refs/tags/v}
      # commit changes to main branch
      - run: git add .; git commit -m "Releases ${GITHUB_REF#refs/tags/v}"; git push origin HEAD:main;
      # publish to NPM
      - run: npm config set '//registry.npmjs.org/:_authToken' "$NPM_TOKEN"
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm whoami
      - run: npm publish --workspaces --access public
